### PR TITLE
Pip installable

### PR DESCRIPTION
**Pull request by p-slash**
This follows the PR in LaCe. Once two branches become part of main, cup1d with lace can be simply set by calling:
`pip install cup1d@git+ssh://git@github.com/igmhub/cup1d.git`.

### CODE REVIEW

**Comment by jchavesmontero** [comment]
```
Installing collected packages: lace, cup1d
  Attempting uninstall: lace
    Found existing installation: lace 1.0.1
    Uninstalling lace-1.0.1:
      Successfully uninstalled lace-1.0.1
  Attempting uninstall: cup1d
    Found existing installation: cup1d 0.1.0
    Uninstalling cup1d-0.1.0:
      Successfully uninstalled cup1d-0.1.0
Successfully installed cup1d-0.1.0 lace-1.0.1
```
As far as I understand, this PR not only installs cup1d but also the **main branch of lace** (I ran `pip install -e .`). If so,  this is not something that we would like because we want to keep developing the code. Is there a way of only installing cup1d now and leaving the lace installation as it is?

**Comment by p-slash** [comment]
Yes, this is annoying. The way I fixed it was to uninstall `pip uninstall lace` and reinstall the local repo with `pip install -e .`. I expected pip to know the local lace installation and not replace it.

**Comment by jchavesmontero** [comment]
Thanks a lot for the quick reply! I think that we could leave with this workaround. @andreufont, what do you think?

**Comment by andreufont** [comment]
I guess it is ok to have a bit of a workaround for those that want to work with cup1d with a non-standard LaCE repo, since only very few of us will have to do this. The instructions should be clearly documented though.

**Review by jchavesmontero — APPROVED** [review]
Green light then!

**Comment by p-slash** [comment]
Let me know when you try my suggestion and if it works @jchavesmontero . Then, you or I can update the instructions before merging.

**Comment by jchavesmontero** [comment]
Sorry for not clarifying this; I tried your solution, and it also works for me. That's why I gave the green light. Could you update the instructions? I am working on a different branch and I am not ready to push my changes

**Comment by p-slash** [comment]
I updated the readme

**Pull request merged**
