### PR TITLE
Ohio QMLE interface updates

### PR DESCRIPTION
**Pull request by p-slash**
I changed the interface to remove hard-coded numbers. You can pass a filename to read any QMLE output file. I fixed poly_p1d imports. They are in lace.utils not lace.emulator, but please check this one.

### CODE REVIEW

**Comment by jchavesmontero** [comment]
Hi @p-slash! I went through the files and everything checks out, I will test it soon. However, before that, is it possible to read the table using numpy instead of panda? It is fine if not, but I prefer using as few external packages as possible.

**Comment by p-slash** [comment]
Unfortunately, numpy doesn't have a suitable function. I use astropy.ascii to read these files actually, but astropy wasn't part of cup1d or lace, so I didn't want to add that. `pandas` is a requirement though, so it already comes with lace I think.

**Comment by jchavesmontero** [comment]
Sorry, I thought it was not a requirement because I have not used it so far. It is perfect then.

**Comment by andreufont** [comment]
Thanks for taking care of this. Could you confirm that we can now read the QMLE EDR results, and if so, could you add a notebook or script showing how to read it and make a plot?

**Comment by andreufont** [comment]
By looking at the commits it doesn't look like this is the case, so I'll open an Issue

**Pull request merged**
